required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
  "k8s.io/gengo/args",
]

[prune]
  go-tests = true
  unused-packages = true

[[prune.project]]
  name = "k8s.io/code-generator"
  unused-packages = false

# Core Kubernetes
[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-KUBEVERSION"
[[override]]
  name = "k8s.io/utils"
  branch = "master"
[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-KUBEVERSION"
[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-KUBEVERSION"
[[override]]
  name = "k8s.io/metrics"
  version = "kubernetes-KUBEVERSION"
[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-KUBEVERSION"
[[override]]
  name = "k8s.io/kubernetes"
  version = "vKUBEVERSION"

# These should get set farther below
# [[override]]
#   name = "k8s.io/apimachinery"
#   version = "kubernetes-KUBEVERSION"
# [[override]]
#   name = "k8s.io/api"
#   version = "kubernetes-KUBEVERSION"
# [[override]]
#   name = "k8s.io/kube-openapi"
#   version = "kubernetes-KUBEVERSION"
