package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ShowConfig ...
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
type ShowConfig struct {
	metav1.TypeMeta `json:",inline"`
	// +optional
	metav1.ObjectMeta `json:"metadata,omitempty"`

	SearchPaths []string `json:"searchPaths,omitempty"`
}

// ShowFormat is the top-level type representing a set of formatter options.
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
type ShowFormat struct {
	metav1.TypeMeta `json:",inline"`
	// +optional
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec ShowFormatSpec `json:"spec,omitempty"`
}

// ShowFormatSpec ...
type ShowFormatSpec struct {
	Aliases        []string               `json:"aliases,omitempty"`
	ComponentKinds []metav1.GroupKind     `json:"componentKinds,omitempty"`
	Defaults       ShowFormatDefaultsSpec `json:"defaults,omitempty"`
	Fields         []FieldSpec            `json:"fields,omitempty"`
}

// ShowFormatDefaultsSpec ...
type ShowFormatDefaultsSpec struct {
	IgnoreUnknownFields bool       `json:"ignoreUnknownFields,omitempty"`
	SortBy              []SortSpec `json:"sortBy"`
}

// ShowFormatList is the autogenerated list type.
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
type ShowFormatList struct {
	metav1.TypeMeta `json:",inline"`
	// +optional
	metav1.ListMeta `json:"metadata,omitempty"`

	Items []ShowFormat `json:"items"`
}

// FieldSpec defines the specification of a column
type FieldSpec struct {
	Name        string `json:"name,omitempty"`
	Label       string `json:"label,omitempty"`
	JSONPath    string `json:"jsonPath,omitempty"`
	Query       string `json:"query,omitempty"`
	Transformer string `json:"transformer,omitempty"`
}

// SortSpec defines a sort by column name and direction
type SortSpec struct {
	Name      string `json:"name,omitempty"`
	Direction string `json:"direction,omitempty"`
}

const (
	SortSpecDirectionAscending  = "Ascending"
	SortSpecDirectionDescending = "Descending"
)
