// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldSpec) DeepCopyInto(out *FieldSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldSpec.
func (in *FieldSpec) DeepCopy() *FieldSpec {
	if in == nil {
		return nil
	}
	out := new(FieldSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShowConfig) DeepCopyInto(out *ShowConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.SearchPaths != nil {
		in, out := &in.SearchPaths, &out.SearchPaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShowConfig.
func (in *ShowConfig) DeepCopy() *ShowConfig {
	if in == nil {
		return nil
	}
	out := new(ShowConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShowConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShowFormatter) DeepCopyInto(out *ShowFormatter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShowFormatter.
func (in *ShowFormatter) DeepCopy() *ShowFormatter {
	if in == nil {
		return nil
	}
	out := new(ShowFormatter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShowFormatter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShowFormatterDefaultsSpec) DeepCopyInto(out *ShowFormatterDefaultsSpec) {
	*out = *in
	if in.SortBy != nil {
		in, out := &in.SortBy, &out.SortBy
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShowFormatterDefaultsSpec.
func (in *ShowFormatterDefaultsSpec) DeepCopy() *ShowFormatterDefaultsSpec {
	if in == nil {
		return nil
	}
	out := new(ShowFormatterDefaultsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShowFormatterList) DeepCopyInto(out *ShowFormatterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ShowFormatter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShowFormatterList.
func (in *ShowFormatterList) DeepCopy() *ShowFormatterList {
	if in == nil {
		return nil
	}
	out := new(ShowFormatterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShowFormatterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShowFormatterSpec) DeepCopyInto(out *ShowFormatterSpec) {
	*out = *in
	if in.Aliases != nil {
		in, out := &in.Aliases, &out.Aliases
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Defaults.DeepCopyInto(&out.Defaults)
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]FieldSpec, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShowFormatterSpec.
func (in *ShowFormatterSpec) DeepCopy() *ShowFormatterSpec {
	if in == nil {
		return nil
	}
	out := new(ShowFormatterSpec)
	in.DeepCopyInto(out)
	return out
}
