apiVersion: k.r8y.dev/v1alpha1
kind: ShowFormat
metadata:
  name: f6fc8259-52c2-4e62-857e-33508d7abf67
spec:
  aliases:
    - resource
    - resources
    - res
    - rsc
  componentKinds:
    - kind: Pod
  defaults:
    ignoreUnknownFields: true
    sortBy:
      - name: name
  fields:
    - name: name
      label: 'NAME'
      jsonPath: '.metadata.name'
      query: '.metadata.name'
    - name: container
      label: 'CONTAINER'
      query: '.spec.containers[].name'
    - name: cpu_limit
      label: 'CPU-LIMIT'
      query: '.spec.containers[] | .resources.limits.cpu'
    - name: mem_limit
      label: 'MEM-LIMIT'
      query: '.spec.containers[] | .resources.limits.memory'
    - name: age
      label: 'AGE'
      query: '.metadata.creationTimestamp'
      transformer: TimeToHumanDuration

